//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceGSV.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoMedia
    {
        public long Id { get; set; }
        public int ObjectTypeId { get; set; }
        public long ObjectId { get; set; }
        public string PhotoLink { get; set; }
        public string MediaLink { get; set; }
        public int Type { get; set; }
    }
}
