//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceGSV.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public long CategoryId { get; set; }
        public long SubCategoryId { get; set; }
        public long Price { get; set; }
        public string Photo { get; set; }
        public ProductStatus Status { get; set; }
        public Nullable<long> PostUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int DictrictId { get; set; }
    }
}
