//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceGSV.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubProductCategory
    {
        public long Id { get; set; }
        public long ProductCategoryId { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
        public SubProductCategoryStatus Status { get; set; }
        public string Link { get; set; }
    }
}
