//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceGSV.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public long Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Passwork { get; set; }
        public int GroupId { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string AvatarPhoto { get; set; }
        public System.DateTime CreateDate { get; set; }
        public UserStatus Status { get; set; }
    }
}
